### ISSUE TITLE
alpha blending - drag effect and colour change

### ISSUE THREAD

**Issue by OlaKenji** [MarkelZ/pygame-render#4]
@MarkelZ Hi! 
I have a question regarding the alpha rendering. I am not sure if it is working as intended or if I simply just overlooked something. I have noticed that there is a "drag" effect when there are layers with alpha < 255 and when moving a sprite. I think the drag effects comes from a rendered sprite from previous frame but is now for some reason semi-transparent. To be clear, the sprite is not suppose to be transparent. I noticed this problem in my game project so I re-produced the issue in this script, which is attached to illustrate the issue/question:
[_alpha.zip](https://github.com/MarkelZ/pygame-render/files/13804718/_alpha.zip)

In this script everything is rendered on a small layer first, and then upscaled to a final layer. The rendering occurs as:
First, the small screen is cleared (screen.clear(0,0,0)). 
Second, a full white background is rendered (colour = (255,255,255,255) ). 
Third, a semi transparent white layer is rendered (colour = (255,255,255,100) ). 
Fourth, a sprite is rendered, that is moving (alpha = 255). 

If you run the script as is, you can clearly see the drag effect and that the background is grey ish. You can confirm it by making the semi-transparent layer to alpha 255 (step three in the list above). Now there is no drag effect and the background is white. The colour change is surprising since the colour of the semi-transparent layer is (255,255,255,100) (i.e. white) and shouldn't make it grey.

You can "solve" the drag effect when the semi-transparent layer is e.g. alpha = 100,  by including engine.clear(0,0,0) after screen.clear(0,0,0) (maybe you are suppose to?). This removes the drag effect, but the problem is that the background is not white but grey (more grey). This is strange given the none transparent white background that is rendered after the .clear() (step 2 in the list above). You can get the desired white background by changing engine.clear(0,0,0) to  engine.clear(255,255,255), but this is not really a fix.

The second issue with the colour when the semi-transparent layer is rendered can be solved if you would apply the the same shader in the in the main loop also (shader = shader_fill) during the rendering of the layers, and not only during the initialisation (if engine.clear() is not set). 
 
All issues mentioned disappears when the semi-transparent layer is set to colour = (255,255,255,255). 

What do you think?

**Comment by MarkelZ** [comment]
@OlaKenji Hey! The engine was doing alpha-blending incorrectly, should be fixed now. Check out [this commit](https://github.com/MarkelZ/pygame-render/commit/5c8200891b108c886b4aabac3cff801f1d035592). I'll upload version 1.2.2 with this fix to PyPI soon.

Thank you very much for letting me know about this bug!

By the way, I noticed that the script creates too many layers/framebuffers, and you can simplify it a bit: [main.py.zip](https://github.com/MarkelZ/pygame-render/files/13805325/main.py.zip). It's just the `main.py` file because I didn't change anything else. Basically, you can use `Layer.clear()` to fill it with a color.

**Comment by OlaKenji** [comment]
@MarkelZ You are right, that fixed the issue. Great! Although, now there is a black outline on textures are blurred. But I think this is due to the bluring shader (I guess the alpha needs to be weighted somehow) and not a bug of the engine. 

Thanks for letting me know about easier way to fill an image. That is indeed better.

**Comment by MarkelZ** [comment]
@OlaKenji I agree, I don't think it's a bug of the engine. Based on what you said, it sounds like the transparent pixels of the sprite have black color (0, 0, 0, 0), so the adjacent pixels become darker when blurring. 

Weighing by the alpha values as you suggest should work:
1. `(r, g, b, a)` becomes `(r*a, g*a, b*a, a)`.
2. Apply the Gaussian kernel as usual.
3. Turn color `(r*a, g*a, b*a, a)` back to `(r, g, b, a)` by dividing by `a`. 
4. Careful when `a=0` not to divide by zero.

I found very similar ideas here https://computergraphics.stackexchange.com/a/8595 and here https://lisyarus.github.io/blog/graphics/2022/04/21/compute-blur.html.

Hope this is useful!
