### ISSUE TITLE
Additional values to the vertex shader?

### ISSUE THREAD

**Issue by PyPixelGames** [MarkelZ/pygame-render#9]
Can i pass additional values to the vertex shader? Like i want to pass Image resolution to there. But the only thing i see is that the render-engine gives 2 values as default:
"
layout(location=0) in vec3 vertexPos;
layout(location=1) in vec2 vertexTexCoord;
"

Can i somehow do it like that? 
"
layout(location=0) in vec3 vertexPos;
layout(location=1) in vec2 vertexTexCoord;
layout(location=2) in vec3 iResolution;
"

Thanks :D

**Comment by MarkelZ** [comment]
Hey @Lukabartovich, thanks for your question! You can send data to the shader using uniforms, check out the [Feature Walkthrough](https://github.com/MarkelZ/pygame-render/wiki/Feature-Walkthrough#uniforms-sending-data-to-the-shader) for more info. So, it should be possible to define the resolution of the image as a uniform of type `vec2` in the vertex/fragment shader,
```glsl
uniform vec2 resolution;
```
and you can send the value from the Python script to the shader like this:
```py
resolution = (900, 600) # The resolution of the image
my_shader = engine.load_shader_from_path(...) # Compile the shader
my_shader['resolution'] = resolution # Send the uniform data
```
Does this work for your use case?

**Comment by PyPixelGames** [comment]
Yes, but that gives data to the ragment shader right. And i would like to give data to the vertex shader. Or can i type uniform in vertex shader too? Btw i am that guy from youtube comments that was trying ti bkit using normal methods. Have found the solution myself :D

**Comment by MarkelZ** [comment]
1. It's not only for the fragment shader, you can send data to the vertex shader too, no problem. Take a look at this: [PyPixelGames.zip](https://github.com/user-attachments/files/16605078/PyPixelGames.zip).
2. I recognized your name from the youtube comments yes! I'm very interested, how did you manage to avoid rewriting all the source code of your game? It's nice to hear that you got it working :)

**Comment by PyPixelGames** [comment]
wow thanks. very cool 👍.Here is how i got it working:  In my game i use small size pixel art and scale it up. Instead of that i use small window, where i draw everything without scaling. The i use set_colorkey function to remove background black color. then i render my shader, turn the small window into texture and draw it upscaling to needed size :D

**Comment by MarkelZ** [comment]
Sounds great, since you're rendering most things onto a small window, the game should run very fast. I'll close this issue now but feel free to open another one if you have new questions!
